# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1685aa164e28186ad30f4c1345a484a605bbd9ffe0f975ee3b14811edb56cbbdd515c8386afab410d054cae2581eb41c8e1af4846d2061f7856ad05f61bf6b44

test:
  secret_key_base: ddeadcf53e9be7b323f4482051fd3fc2aff0551d7a857088a125d03264566d4779edd33f7321bcf72e3433d99db2b3448dc54c9eaf6663f9936075fe5683249f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
